name = "my-worker-dev"

account_id = "<YOUR ACCOUNTID>"
workers_dev = true

node_compat = true
compatibility_date = "2022-11-30"


# Define top-level environment variables
# under the `[vars]` block using
# the `key = "value"` format
[vars]
MONGO_URL="mongodb+srv://abetrain:I9EkczZ37ENGbQE7@web2.cry78.mongodb.net/?retryWrites=true&w=majority"
MONGO_API_KEY="boMDfydlMZVtkHMsSUsEM7TdSgSYg44oeZeA5Fz2Genkz0zlipml3EXn9y3mOl1v"
DATABASE_NAME="countries"
SHUFFLE_KEY="522"
CRYPTO_KEY="ee53e68c3074206a002bf01333b047d5"
VITE_CRYPTO_KEY="ee53e68c3074206a002bf01333b047d5"
VITE_GOOGLE_CLIENT_ID="343850552080-rv0ul9jc53m0v5mj9ef3f1dpcv7hm6va.apps.googleusercontent.com"
GOOGLE_CLIENT_ID="343850552080-rv0ul9jc53m0v5mj9ef3f1dpcv7hm6va.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET="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"
GOOGLE_REFRESH_TOKEN="1//04ddVfyseoPYsCgYIARAAGAQSNwF-L9IrqlWPo9wIz_t7tiN7ibOGU-cIyfLP7d0pZS11R4vfWJ2a8mRjjrnDoacbCkKefMpo0fA"
MY_EMAIL="abraham.train@gmail.com"

# Override values for `--env production` usage
[env.production]
name = "my-worker-production"
[env.production.vars]
API_TOKEN = "example_production_token"
STRIPE_TOKEN = "pk_xyz1234"
